/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />
import { BigNumber } from 'bignumber.js';

export interface ChallengeableContract extends Truffle.Contract<ChallengeableInstance> {
  'new'(meta?: Truffle.TransactionDetails): Promise<ChallengeableInstance>;
}

export interface ConfiguratedContract extends Truffle.Contract<ConfiguratedInstance> {
  'new'(meta?: Truffle.TransactionDetails): Promise<ConfiguratedInstance>;
}

export interface CoordinatableContract extends Truffle.Contract<CoordinatableInstance> {
  'new'(meta?: Truffle.TransactionDetails): Promise<CoordinatableInstance>;
}

export interface IChallengeableContract extends Truffle.Contract<IChallengeableInstance> {
  'new'(meta?: Truffle.TransactionDetails): Promise<IChallengeableInstance>;
}

export interface ICoordinatableContract extends Truffle.Contract<ICoordinatableInstance> {
  'new'(meta?: Truffle.TransactionDetails): Promise<ICoordinatableInstance>;
}

export interface IERC20Contract extends Truffle.Contract<IERC20Instance> {
  'new'(meta?: Truffle.TransactionDetails): Promise<IERC20Instance>;
}

export interface IMigratableContract extends Truffle.Contract<IMigratableInstance> {
  'new'(meta?: Truffle.TransactionDetails): Promise<IMigratableInstance>;
}

export interface IRollUpableContract extends Truffle.Contract<IRollUpableInstance> {
  'new'(meta?: Truffle.TransactionDetails): Promise<IRollUpableInstance>;
}

export interface ISetupWizardContract extends Truffle.Contract<ISetupWizardInstance> {
  'new'(meta?: Truffle.TransactionDetails): Promise<ISetupWizardInstance>;
}

export interface IUserInteractableContract extends Truffle.Contract<IUserInteractableInstance> {
  'new'(meta?: Truffle.TransactionDetails): Promise<IUserInteractableInstance>;
}

export interface Layer2Contract extends Truffle.Contract<Layer2Instance> {
  'new'(meta?: Truffle.TransactionDetails): Promise<Layer2Instance>;
}

export interface Layer2ControllerContract extends Truffle.Contract<Layer2ControllerInstance> {
  'new'(meta?: Truffle.TransactionDetails): Promise<Layer2ControllerInstance>;
}

export interface MigratableContract extends Truffle.Contract<MigratableInstance> {
  'new'(meta?: Truffle.TransactionDetails): Promise<MigratableInstance>;
}

export interface MigrationsContract extends Truffle.Contract<MigrationsInstance> {
  'new'(meta?: Truffle.TransactionDetails): Promise<MigrationsInstance>;
}

export interface MiMCContract extends Truffle.Contract<MiMCInstance> {
  'new'(meta?: Truffle.TransactionDetails): Promise<MiMCInstance>;
}

export interface RollUpableContract extends Truffle.Contract<RollUpableInstance> {
  'new'(meta?: Truffle.TransactionDetails): Promise<RollUpableInstance>;
}

export interface SetupWizardContract extends Truffle.Contract<SetupWizardInstance> {
  'new'(_setupWizard: string | BigNumber, meta?: Truffle.TransactionDetails): Promise<SetupWizardInstance>;
}

export interface SMT256Contract extends Truffle.Contract<SMT256Instance> {
  'new'(meta?: Truffle.TransactionDetails): Promise<SMT256Instance>;
}

export interface TestERC20Contract extends Truffle.Contract<TestERC20Instance> {
  'new'(initialSupply: number | BigNumber | string, meta?: Truffle.TransactionDetails): Promise<TestERC20Instance>;
}

export interface UserInteractableContract extends Truffle.Contract<UserInteractableInstance> {
  'new'(meta?: Truffle.TransactionDetails): Promise<UserInteractableInstance>;
}

export interface ZkOptimisticRollUpContract extends Truffle.Contract<ZkOptimisticRollUpInstance> {
  'new'(_setupWizard: string | BigNumber, meta?: Truffle.TransactionDetails): Promise<ZkOptimisticRollUpInstance>;
}

export interface MiMCContract extends Truffle.Contract<MiMCInstance> {
  'new'(meta?: Truffle.TransactionDetails): Promise<MiMCInstance>;
}

export interface TestERC20Contract extends Truffle.Contract<TestERC20Instance> {
  'new'(initialSupply: number | BigNumber | string, meta?: Truffle.TransactionDetails): Promise<TestERC20Instance>;
}

export interface ChallengeableInstance extends Truffle.ContractInstance {
  CHALLENGE_LIMIT(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  CHALLENGE_PERIOD(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  MINIMUM_STAKE(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  POOL_SIZE(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  REF_DEPTH(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  asset(txDetails?: Truffle.TransactionDetails): Promise<[string, string]>;

  chain(txDetails?: Truffle.TransactionDetails): Promise<[string, BigNumber]>;

  challengeUTXORollUp: {
    (utxoRollUpId: number | BigNumber | string, deposits: (number | BigNumber | string)[], arg2: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse
    >;
    call(
      utxoRollUpId: number | BigNumber | string,
      deposits: (number | BigNumber | string)[],
      arg2: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      utxoRollUpId: number | BigNumber | string,
      deposits: (number | BigNumber | string)[],
      arg2: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      utxoRollUpId: number | BigNumber | string,
      deposits: (number | BigNumber | string)[],
      arg2: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  challengeNullifierRollUp: {
    (
      nullifierRollUpId: number | BigNumber | string,
      numOfNullifiers: number | BigNumber | string,
      arg2: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse>;
    call(
      nullifierRollUpId: number | BigNumber | string,
      numOfNullifiers: number | BigNumber | string,
      arg2: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      nullifierRollUpId: number | BigNumber | string,
      numOfNullifiers: number | BigNumber | string,
      arg2: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      nullifierRollUpId: number | BigNumber | string,
      numOfNullifiers: number | BigNumber | string,
      arg2: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  challengeDepositRoot: {
    (deposits: (number | BigNumber | string)[], arg1: string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(deposits: (number | BigNumber | string)[], arg1: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(deposits: (number | BigNumber | string)[], arg1: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(deposits: (number | BigNumber | string)[], arg1: string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  challengeTransferRoot: {
    (arg0: string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  challengeWithdrawalRoot: {
    (arg0: string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  challengeMigrationRoot: {
    (arg0: string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  challengeTotalFee: {
    (arg0: string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  challengeInclusion: {
    (
      txType: number | BigNumber | string,
      txIndex: number | BigNumber | string,
      refIndex: number | BigNumber | string,
      arg3: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse>;
    call(
      txType: number | BigNumber | string,
      txIndex: number | BigNumber | string,
      refIndex: number | BigNumber | string,
      arg3: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      txType: number | BigNumber | string,
      txIndex: number | BigNumber | string,
      refIndex: number | BigNumber | string,
      arg3: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      txType: number | BigNumber | string,
      txIndex: number | BigNumber | string,
      refIndex: number | BigNumber | string,
      arg3: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  challengeTransaction: {
    (txType: number | BigNumber | string, index: number | BigNumber | string, arg2: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse
    >;
    call(txType: number | BigNumber | string, index: number | BigNumber | string, arg2: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(
      txType: number | BigNumber | string,
      index: number | BigNumber | string,
      arg2: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(txType: number | BigNumber | string, index: number | BigNumber | string, arg2: string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  challengeUsedNullifier: {
    (
      txType: number | BigNumber | string,
      txIndex: number | BigNumber | string,
      nullifierIndex: number | BigNumber | string,
      sibling: (string | BigNumber)[],
      arg4: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse>;
    call(
      txType: number | BigNumber | string,
      txIndex: number | BigNumber | string,
      nullifierIndex: number | BigNumber | string,
      sibling: (string | BigNumber)[],
      arg4: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      txType: number | BigNumber | string,
      txIndex: number | BigNumber | string,
      nullifierIndex: number | BigNumber | string,
      sibling: (string | BigNumber)[],
      arg4: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      txType: number | BigNumber | string,
      txIndex: number | BigNumber | string,
      nullifierIndex: number | BigNumber | string,
      sibling: (string | BigNumber)[],
      arg4: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  challengeDuplicatedNullifier: {
    (nullifier: string | BigNumber, arg1: string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(nullifier: string | BigNumber, arg1: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(nullifier: string | BigNumber, arg1: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(nullifier: string | BigNumber, arg1: string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  isValidRef(l2BlockHash: string | BigNumber, ref: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<boolean>;
}

export interface ConfiguratedInstance extends Truffle.ContractInstance {
  CHALLENGE_LIMIT(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  CHALLENGE_PERIOD(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  MINIMUM_STAKE(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  POOL_SIZE(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  REF_DEPTH(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;
}

export interface CoordinatableInstance extends Truffle.ContractInstance {
  CHALLENGE_LIMIT(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  CHALLENGE_PERIOD(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  MINIMUM_STAKE(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  POOL_SIZE(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  REF_DEPTH(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  asset(txDetails?: Truffle.TransactionDetails): Promise<[string, string]>;

  chain(txDetails?: Truffle.TransactionDetails): Promise<[string, BigNumber]>;

  register: {
    (txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  deregister: {
    (txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  propose: {
    (arg0: string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  finalize: {
    (arg0: string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  withdrawReward: {
    (amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  isProposable(proposerAddr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<boolean>;
}

export interface IChallengeableInstance extends Truffle.ContractInstance {
  challengeUTXORollUp: {
    (proofId: number | BigNumber | string, deposits: (number | BigNumber | string)[], submission: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse
    >;
    call(
      proofId: number | BigNumber | string,
      deposits: (number | BigNumber | string)[],
      submission: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      proofId: number | BigNumber | string,
      deposits: (number | BigNumber | string)[],
      submission: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      proofId: number | BigNumber | string,
      deposits: (number | BigNumber | string)[],
      submission: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  challengeNullifierRollUp: {
    (proofId: number | BigNumber | string, siblings: (string | BigNumber)[][], submission: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse
    >;
    call(proofId: number | BigNumber | string, siblings: (string | BigNumber)[][], submission: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(
      proofId: number | BigNumber | string,
      siblings: (string | BigNumber)[][],
      submission: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      proofId: number | BigNumber | string,
      siblings: (string | BigNumber)[][],
      submission: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  challengeDepositRoot: {
    (deposits: (number | BigNumber | string)[], submission: string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(deposits: (number | BigNumber | string)[], submission: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(deposits: (number | BigNumber | string)[], submission: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(deposits: (number | BigNumber | string)[], submission: string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  challengeTransferRoot: {
    (submission: string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(submission: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(submission: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(submission: string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  challengeWithdrawalRoot: {
    (submission: string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(submission: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(submission: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(submission: string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  challengeMigrationRoot: {
    (submission: string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(submission: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(submission: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(submission: string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  challengeTotalFee: {
    (submission: string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(submission: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(submission: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(submission: string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  challengeInclusion: {
    (
      txType: number | BigNumber | string,
      txIndex: number | BigNumber | string,
      refIndex: number | BigNumber | string,
      submission: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse>;
    call(
      txType: number | BigNumber | string,
      txIndex: number | BigNumber | string,
      refIndex: number | BigNumber | string,
      submission: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      txType: number | BigNumber | string,
      txIndex: number | BigNumber | string,
      refIndex: number | BigNumber | string,
      submission: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      txType: number | BigNumber | string,
      txIndex: number | BigNumber | string,
      refIndex: number | BigNumber | string,
      submission: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  challengeTransaction: {
    (txType: number | BigNumber | string, txIndex: number | BigNumber | string, submission: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse
    >;
    call(txType: number | BigNumber | string, txIndex: number | BigNumber | string, submission: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(
      txType: number | BigNumber | string,
      txIndex: number | BigNumber | string,
      submission: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      txType: number | BigNumber | string,
      txIndex: number | BigNumber | string,
      submission: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  challengeUsedNullifier: {
    (
      txType: number | BigNumber | string,
      txIndex: number | BigNumber | string,
      nullifierIndex: number | BigNumber | string,
      sibling: (string | BigNumber)[],
      submission: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse>;
    call(
      txType: number | BigNumber | string,
      txIndex: number | BigNumber | string,
      nullifierIndex: number | BigNumber | string,
      sibling: (string | BigNumber)[],
      submission: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      txType: number | BigNumber | string,
      txIndex: number | BigNumber | string,
      nullifierIndex: number | BigNumber | string,
      sibling: (string | BigNumber)[],
      submission: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      txType: number | BigNumber | string,
      txIndex: number | BigNumber | string,
      nullifierIndex: number | BigNumber | string,
      sibling: (string | BigNumber)[],
      submission: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  challengeDuplicatedNullifier: {
    (nullifier: string | BigNumber, submission: string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(nullifier: string | BigNumber, submission: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(nullifier: string | BigNumber, submission: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(nullifier: string | BigNumber, submission: string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  isValidRef(l2BlockHash: string | BigNumber, ref: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<boolean>;
}

export interface ICoordinatableInstance extends Truffle.ContractInstance {
  register: {
    (txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  deregister: {
    (txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  propose: {
    (submission: string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(submission: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(submission: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(submission: string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  finalize: {
    (submission: string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(submission: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(submission: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(submission: string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  withdrawReward: {
    (amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  isProposable(proposerAddr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<boolean>;
}

export interface IERC20Instance extends Truffle.ContractInstance {
  transfer: {
    (recipient: string | BigNumber, amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(recipient: string | BigNumber, amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<boolean>;
    sendTransaction(recipient: string | BigNumber, amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(recipient: string | BigNumber, amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  transferFrom: {
    (sender: string | BigNumber, recipient: string | BigNumber, amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse
    >;
    call(
      sender: string | BigNumber,
      recipient: string | BigNumber,
      amount: number | BigNumber | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;
    sendTransaction(
      sender: string | BigNumber,
      recipient: string | BigNumber,
      amount: number | BigNumber | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      sender: string | BigNumber,
      recipient: string | BigNumber,
      amount: number | BigNumber | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };
}

export interface IMigratableInstance extends Truffle.ContractInstance {
  migrateTo: {
    (migrationId: number | BigNumber | string, to: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(migrationId: number | BigNumber | string, to: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(migrationId: number | BigNumber | string, to: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(migrationId: number | BigNumber | string, to: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };
}

export interface IRollUpableInstance extends Truffle.ContractInstance {
  newProofOfUTXORollUp: {
    (
      startingRoot: number | BigNumber | string,
      startingIndex: number | BigNumber | string,
      initialSiblings: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse>;
    call(
      startingRoot: number | BigNumber | string,
      startingIndex: number | BigNumber | string,
      initialSiblings: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      startingRoot: number | BigNumber | string,
      startingIndex: number | BigNumber | string,
      initialSiblings: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      startingRoot: number | BigNumber | string,
      startingIndex: number | BigNumber | string,
      initialSiblings: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  newProofOfNullifierRollUp: {
    (prevRoot: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(prevRoot: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(prevRoot: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(prevRoot: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  newProofOfWithdrawalRollUp: {
    (startingRoot: number | BigNumber | string, startingIndex: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse
    >;
    call(startingRoot: number | BigNumber | string, startingIndex: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(
      startingRoot: number | BigNumber | string,
      startingIndex: number | BigNumber | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(startingRoot: number | BigNumber | string, startingIndex: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  updateProofOfUTXORollUp: {
    (id: number | BigNumber | string, leaves: (number | BigNumber | string)[], txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(id: number | BigNumber | string, leaves: (number | BigNumber | string)[], txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(id: number | BigNumber | string, leaves: (number | BigNumber | string)[], txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(id: number | BigNumber | string, leaves: (number | BigNumber | string)[], txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  updateProofOfNullifierRollUp: {
    (id: number | BigNumber | string, leaves: (string | BigNumber)[], siblings: (string | BigNumber)[][], txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse
    >;
    call(
      id: number | BigNumber | string,
      leaves: (string | BigNumber)[],
      siblings: (string | BigNumber)[][],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      id: number | BigNumber | string,
      leaves: (string | BigNumber)[],
      siblings: (string | BigNumber)[][],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      id: number | BigNumber | string,
      leaves: (string | BigNumber)[],
      siblings: (string | BigNumber)[][],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  updateProofOfWithdrawalRollUp: {
    (
      id: number | BigNumber | string,
      initialSiblings: (number | BigNumber | string)[],
      leaves: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse>;
    call(
      id: number | BigNumber | string,
      initialSiblings: (number | BigNumber | string)[],
      leaves: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      id: number | BigNumber | string,
      initialSiblings: (number | BigNumber | string)[],
      leaves: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      id: number | BigNumber | string,
      initialSiblings: (number | BigNumber | string)[],
      leaves: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };
}

export interface ISetupWizardInstance extends Truffle.ContractInstance {
  registerERC20: {
    (_erc20: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(_erc20: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(_erc20: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(_erc20: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  registerUIContract: {
    (addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  registerRollUpContract: {
    (addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  registerChallengeContract: {
    (addr: string | BigNumber, sigs: (string | BigNumber)[], txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(addr: string | BigNumber, sigs: (string | BigNumber)[], txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(addr: string | BigNumber, sigs: (string | BigNumber)[], txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(addr: string | BigNumber, sigs: (string | BigNumber)[], txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  registerMigrateContract: {
    (addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  registerVk: {
    (
      txType: number | BigNumber | string,
      numOfInputs: number | BigNumber | string,
      numOfOutputs: number | BigNumber | string,
      alfa1: (number | BigNumber | string)[],
      beta2: (number | BigNumber | string)[][],
      gamma2: (number | BigNumber | string)[][],
      delta2: (number | BigNumber | string)[][],
      ic: (number | BigNumber | string)[][],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse>;
    call(
      txType: number | BigNumber | string,
      numOfInputs: number | BigNumber | string,
      numOfOutputs: number | BigNumber | string,
      alfa1: (number | BigNumber | string)[],
      beta2: (number | BigNumber | string)[][],
      gamma2: (number | BigNumber | string)[][],
      delta2: (number | BigNumber | string)[][],
      ic: (number | BigNumber | string)[][],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      txType: number | BigNumber | string,
      numOfInputs: number | BigNumber | string,
      numOfOutputs: number | BigNumber | string,
      alfa1: (number | BigNumber | string)[],
      beta2: (number | BigNumber | string)[][],
      gamma2: (number | BigNumber | string)[][],
      delta2: (number | BigNumber | string)[][],
      ic: (number | BigNumber | string)[][],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      txType: number | BigNumber | string,
      numOfInputs: number | BigNumber | string,
      numOfOutputs: number | BigNumber | string,
      alfa1: (number | BigNumber | string)[],
      beta2: (number | BigNumber | string)[][],
      gamma2: (number | BigNumber | string)[][],
      delta2: (number | BigNumber | string)[][],
      ic: (number | BigNumber | string)[][],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  allowMigrants: {
    (migrants: (string | BigNumber)[], txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(migrants: (string | BigNumber)[], txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(migrants: (string | BigNumber)[], txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(migrants: (string | BigNumber)[], txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  completeSetup: {
    (txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };
}

export interface IUserInteractableInstance extends Truffle.ContractInstance {
  deposit: {
    (
      note: number | BigNumber | string,
      amount: number | BigNumber | string,
      fee: number | BigNumber | string,
      pubKey: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse>;
    call(
      note: number | BigNumber | string,
      amount: number | BigNumber | string,
      fee: number | BigNumber | string,
      pubKey: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      note: number | BigNumber | string,
      amount: number | BigNumber | string,
      fee: number | BigNumber | string,
      pubKey: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      note: number | BigNumber | string,
      amount: number | BigNumber | string,
      fee: number | BigNumber | string,
      pubKey: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  withdraw: {
    (
      amount: number | BigNumber | string,
      proofHash: string | BigNumber,
      rootIndex: number | BigNumber | string,
      leafIndex: number | BigNumber | string,
      siblings: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse>;
    call(
      amount: number | BigNumber | string,
      proofHash: string | BigNumber,
      rootIndex: number | BigNumber | string,
      leafIndex: number | BigNumber | string,
      siblings: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      amount: number | BigNumber | string,
      proofHash: string | BigNumber,
      rootIndex: number | BigNumber | string,
      leafIndex: number | BigNumber | string,
      siblings: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      amount: number | BigNumber | string,
      proofHash: string | BigNumber,
      rootIndex: number | BigNumber | string,
      leafIndex: number | BigNumber | string,
      siblings: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  withdrawUsingSignature: {
    (
      amount: number | BigNumber | string,
      to: string | BigNumber,
      proofHash: string | BigNumber,
      rootIndex: number | BigNumber | string,
      leafIndex: number | BigNumber | string,
      siblings: (number | BigNumber | string)[],
      v: number | BigNumber | string,
      r: string | BigNumber,
      s: string | BigNumber,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse>;
    call(
      amount: number | BigNumber | string,
      to: string | BigNumber,
      proofHash: string | BigNumber,
      rootIndex: number | BigNumber | string,
      leafIndex: number | BigNumber | string,
      siblings: (number | BigNumber | string)[],
      v: number | BigNumber | string,
      r: string | BigNumber,
      s: string | BigNumber,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      amount: number | BigNumber | string,
      to: string | BigNumber,
      proofHash: string | BigNumber,
      rootIndex: number | BigNumber | string,
      leafIndex: number | BigNumber | string,
      siblings: (number | BigNumber | string)[],
      v: number | BigNumber | string,
      r: string | BigNumber,
      s: string | BigNumber,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      amount: number | BigNumber | string,
      to: string | BigNumber,
      proofHash: string | BigNumber,
      rootIndex: number | BigNumber | string,
      leafIndex: number | BigNumber | string,
      siblings: (number | BigNumber | string)[],
      v: number | BigNumber | string,
      r: string | BigNumber,
      s: string | BigNumber,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };
}

export interface Layer2Instance extends Truffle.ContractInstance {
  CHALLENGE_LIMIT(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  CHALLENGE_PERIOD(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  MINIMUM_STAKE(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  POOL_SIZE(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  REF_DEPTH(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  asset(txDetails?: Truffle.TransactionDetails): Promise<[string, string]>;

  chain(txDetails?: Truffle.TransactionDetails): Promise<[string, BigNumber]>;
}

export interface Layer2ControllerInstance extends Truffle.ContractInstance {
  CHALLENGE_LIMIT(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  CHALLENGE_PERIOD(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  MINIMUM_STAKE(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  POOL_SIZE(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  REF_DEPTH(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  asset(txDetails?: Truffle.TransactionDetails): Promise<[string, string]>;

  chain(txDetails?: Truffle.TransactionDetails): Promise<[string, BigNumber]>;

  deregister: {
    (txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  finalize: {
    (arg0: string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  isProposable(proposerAddr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<boolean>;

  propose: {
    (arg0: string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  proxied(arg0: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<string>;

  register: {
    (txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  withdrawReward: {
    (amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };
}

export interface MigratableInstance extends Truffle.ContractInstance {
  CHALLENGE_LIMIT(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  CHALLENGE_PERIOD(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  MINIMUM_STAKE(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  POOL_SIZE(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  REF_DEPTH(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  asset(txDetails?: Truffle.TransactionDetails): Promise<[string, string]>;

  chain(txDetails?: Truffle.TransactionDetails): Promise<[string, BigNumber]>;

  migrate: {
    (
      amount: number | BigNumber | string,
      fee: number | BigNumber | string,
      length: number | BigNumber | string,
      mergedLeaves: string | BigNumber,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse>;
    call(
      amount: number | BigNumber | string,
      fee: number | BigNumber | string,
      length: number | BigNumber | string,
      mergedLeaves: string | BigNumber,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      amount: number | BigNumber | string,
      fee: number | BigNumber | string,
      length: number | BigNumber | string,
      mergedLeaves: string | BigNumber,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      amount: number | BigNumber | string,
      fee: number | BigNumber | string,
      length: number | BigNumber | string,
      mergedLeaves: string | BigNumber,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  migrateTo: {
    (migrationId: number | BigNumber | string, to: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(migrationId: number | BigNumber | string, to: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(migrationId: number | BigNumber | string, to: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(migrationId: number | BigNumber | string, to: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };
}

export interface MigrationsInstance extends Truffle.ContractInstance {
  last_completed_migration(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  owner(txDetails?: Truffle.TransactionDetails): Promise<string>;

  setCompleted: {
    (completed: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(completed: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(completed: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(completed: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  upgrade: {
    (new_address: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(new_address: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(new_address: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(new_address: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };
}

export interface MiMCInstance extends Truffle.ContractInstance {
  MiMCSponge(
    xL_in: number | BigNumber | string,
    xR_in: number | BigNumber | string,
    k: number | BigNumber | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<[BigNumber, BigNumber]>;
}

export interface RollUpableInstance extends Truffle.ContractInstance {
  CHALLENGE_LIMIT(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  CHALLENGE_PERIOD(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  MINIMUM_STAKE(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  POOL_SIZE(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  REF_DEPTH(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  asset(txDetails?: Truffle.TransactionDetails): Promise<[string, string]>;

  chain(txDetails?: Truffle.TransactionDetails): Promise<[string, BigNumber]>;

  newProofOfUTXORollUp: {
    (
      startingRoot: number | BigNumber | string,
      startingIndex: number | BigNumber | string,
      initialSiblings: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse>;
    call(
      startingRoot: number | BigNumber | string,
      startingIndex: number | BigNumber | string,
      initialSiblings: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      startingRoot: number | BigNumber | string,
      startingIndex: number | BigNumber | string,
      initialSiblings: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      startingRoot: number | BigNumber | string,
      startingIndex: number | BigNumber | string,
      initialSiblings: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  newProofOfNullifierRollUp: {
    (prevRoot: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(prevRoot: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(prevRoot: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(prevRoot: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  newProofOfWithdrawalRollUp: {
    (startingRoot: number | BigNumber | string, startingIndex: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse
    >;
    call(startingRoot: number | BigNumber | string, startingIndex: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(
      startingRoot: number | BigNumber | string,
      startingIndex: number | BigNumber | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(startingRoot: number | BigNumber | string, startingIndex: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  updateProofOfUTXORollUp: {
    (id: number | BigNumber | string, leaves: (number | BigNumber | string)[], txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(id: number | BigNumber | string, leaves: (number | BigNumber | string)[], txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(id: number | BigNumber | string, leaves: (number | BigNumber | string)[], txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(id: number | BigNumber | string, leaves: (number | BigNumber | string)[], txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  updateProofOfNullifierRollUp: {
    (id: number | BigNumber | string, leaves: (string | BigNumber)[], siblings: (string | BigNumber)[][], txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse
    >;
    call(
      id: number | BigNumber | string,
      leaves: (string | BigNumber)[],
      siblings: (string | BigNumber)[][],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      id: number | BigNumber | string,
      leaves: (string | BigNumber)[],
      siblings: (string | BigNumber)[][],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      id: number | BigNumber | string,
      leaves: (string | BigNumber)[],
      siblings: (string | BigNumber)[][],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  updateProofOfWithdrawalRollUp: {
    (
      id: number | BigNumber | string,
      initialSiblings: (number | BigNumber | string)[],
      leaves: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse>;
    call(
      id: number | BigNumber | string,
      initialSiblings: (number | BigNumber | string)[],
      leaves: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      id: number | BigNumber | string,
      initialSiblings: (number | BigNumber | string)[],
      leaves: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      id: number | BigNumber | string,
      initialSiblings: (number | BigNumber | string)[],
      leaves: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };
}

export interface SetupWizardInstance extends Truffle.ContractInstance {
  CHALLENGE_LIMIT(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  CHALLENGE_PERIOD(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  MINIMUM_STAKE(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  POOL_SIZE(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  REF_DEPTH(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  asset(txDetails?: Truffle.TransactionDetails): Promise<[string, string]>;

  chain(txDetails?: Truffle.TransactionDetails): Promise<[string, BigNumber]>;

  deregister: {
    (txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  finalize: {
    (arg0: string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  isProposable(proposerAddr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<boolean>;

  propose: {
    (arg0: string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  proxied(arg0: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<string>;

  register: {
    (txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  withdrawReward: {
    (amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  registerERC20: {
    (_erc20: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(_erc20: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(_erc20: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(_erc20: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  registerVk: {
    (
      txType: number | BigNumber | string,
      numOfInputs: number | BigNumber | string,
      numOfOutputs: number | BigNumber | string,
      alfa1: (number | BigNumber | string)[],
      beta2: (number | BigNumber | string)[][],
      gamma2: (number | BigNumber | string)[][],
      delta2: (number | BigNumber | string)[][],
      ic: (number | BigNumber | string)[][],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse>;
    call(
      txType: number | BigNumber | string,
      numOfInputs: number | BigNumber | string,
      numOfOutputs: number | BigNumber | string,
      alfa1: (number | BigNumber | string)[],
      beta2: (number | BigNumber | string)[][],
      gamma2: (number | BigNumber | string)[][],
      delta2: (number | BigNumber | string)[][],
      ic: (number | BigNumber | string)[][],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      txType: number | BigNumber | string,
      numOfInputs: number | BigNumber | string,
      numOfOutputs: number | BigNumber | string,
      alfa1: (number | BigNumber | string)[],
      beta2: (number | BigNumber | string)[][],
      gamma2: (number | BigNumber | string)[][],
      delta2: (number | BigNumber | string)[][],
      ic: (number | BigNumber | string)[][],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      txType: number | BigNumber | string,
      numOfInputs: number | BigNumber | string,
      numOfOutputs: number | BigNumber | string,
      alfa1: (number | BigNumber | string)[],
      beta2: (number | BigNumber | string)[][],
      gamma2: (number | BigNumber | string)[][],
      delta2: (number | BigNumber | string)[][],
      ic: (number | BigNumber | string)[][],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  connectUserInteractable: {
    (addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  connecRollUpable: {
    (addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  connectChallengeable: {
    (addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  connectMigratable: {
    (addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  allowMigrants: {
    (migrants: (string | BigNumber)[], txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(migrants: (string | BigNumber)[], txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(migrants: (string | BigNumber)[], txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(migrants: (string | BigNumber)[], txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  completeSetup: {
    (txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };
}

export interface SMT256Instance extends Truffle.ContractInstance {
  EXIST(txDetails?: Truffle.TransactionDetails): Promise<string>;

  NON_EXIST(txDetails?: Truffle.TransactionDetails): Promise<string>;
}

export interface TestERC20Instance extends Truffle.ContractInstance {
  allowance(owner: string | BigNumber, spender: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  approve: {
    (spender: string | BigNumber, amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(spender: string | BigNumber, amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<boolean>;
    sendTransaction(spender: string | BigNumber, amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(spender: string | BigNumber, amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  balanceOf(account: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  decimals(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  decreaseAllowance: {
    (spender: string | BigNumber, subtractedValue: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(spender: string | BigNumber, subtractedValue: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<boolean>;
    sendTransaction(spender: string | BigNumber, subtractedValue: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(spender: string | BigNumber, subtractedValue: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  increaseAllowance: {
    (spender: string | BigNumber, addedValue: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(spender: string | BigNumber, addedValue: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<boolean>;
    sendTransaction(spender: string | BigNumber, addedValue: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(spender: string | BigNumber, addedValue: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  name(txDetails?: Truffle.TransactionDetails): Promise<string>;

  symbol(txDetails?: Truffle.TransactionDetails): Promise<string>;

  totalSupply(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  transfer: {
    (recipient: string | BigNumber, amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(recipient: string | BigNumber, amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<boolean>;
    sendTransaction(recipient: string | BigNumber, amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(recipient: string | BigNumber, amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  transferFrom: {
    (sender: string | BigNumber, recipient: string | BigNumber, amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse
    >;
    call(
      sender: string | BigNumber,
      recipient: string | BigNumber,
      amount: number | BigNumber | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;
    sendTransaction(
      sender: string | BigNumber,
      recipient: string | BigNumber,
      amount: number | BigNumber | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      sender: string | BigNumber,
      recipient: string | BigNumber,
      amount: number | BigNumber | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };
}

export interface UserInteractableInstance extends Truffle.ContractInstance {
  CHALLENGE_LIMIT(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  CHALLENGE_PERIOD(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  MINIMUM_STAKE(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  POOL_SIZE(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  REF_DEPTH(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  asset(txDetails?: Truffle.TransactionDetails): Promise<[string, string]>;

  chain(txDetails?: Truffle.TransactionDetails): Promise<[string, BigNumber]>;

  deposit: {
    (
      note: number | BigNumber | string,
      amount: number | BigNumber | string,
      fee: number | BigNumber | string,
      pubKey: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse>;
    call(
      note: number | BigNumber | string,
      amount: number | BigNumber | string,
      fee: number | BigNumber | string,
      pubKey: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      note: number | BigNumber | string,
      amount: number | BigNumber | string,
      fee: number | BigNumber | string,
      pubKey: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      note: number | BigNumber | string,
      amount: number | BigNumber | string,
      fee: number | BigNumber | string,
      pubKey: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  withdraw: {
    (
      amount: number | BigNumber | string,
      proofHash: string | BigNumber,
      rootIndex: number | BigNumber | string,
      leafIndex: number | BigNumber | string,
      siblings: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse>;
    call(
      amount: number | BigNumber | string,
      proofHash: string | BigNumber,
      rootIndex: number | BigNumber | string,
      leafIndex: number | BigNumber | string,
      siblings: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      amount: number | BigNumber | string,
      proofHash: string | BigNumber,
      rootIndex: number | BigNumber | string,
      leafIndex: number | BigNumber | string,
      siblings: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      amount: number | BigNumber | string,
      proofHash: string | BigNumber,
      rootIndex: number | BigNumber | string,
      leafIndex: number | BigNumber | string,
      siblings: (number | BigNumber | string)[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  withdrawUsingSignature: {
    (
      amount: number | BigNumber | string,
      to: string | BigNumber,
      proofHash: string | BigNumber,
      rootIndex: number | BigNumber | string,
      leafIndex: number | BigNumber | string,
      siblings: (number | BigNumber | string)[],
      v: number | BigNumber | string,
      r: string | BigNumber,
      s: string | BigNumber,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse>;
    call(
      amount: number | BigNumber | string,
      to: string | BigNumber,
      proofHash: string | BigNumber,
      rootIndex: number | BigNumber | string,
      leafIndex: number | BigNumber | string,
      siblings: (number | BigNumber | string)[],
      v: number | BigNumber | string,
      r: string | BigNumber,
      s: string | BigNumber,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      amount: number | BigNumber | string,
      to: string | BigNumber,
      proofHash: string | BigNumber,
      rootIndex: number | BigNumber | string,
      leafIndex: number | BigNumber | string,
      siblings: (number | BigNumber | string)[],
      v: number | BigNumber | string,
      r: string | BigNumber,
      s: string | BigNumber,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      amount: number | BigNumber | string,
      to: string | BigNumber,
      proofHash: string | BigNumber,
      rootIndex: number | BigNumber | string,
      leafIndex: number | BigNumber | string,
      siblings: (number | BigNumber | string)[],
      v: number | BigNumber | string,
      r: string | BigNumber,
      s: string | BigNumber,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };
}

export interface ZkOptimisticRollUpInstance extends Truffle.ContractInstance {
  CHALLENGE_LIMIT(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  CHALLENGE_PERIOD(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  MINIMUM_STAKE(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  POOL_SIZE(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  REF_DEPTH(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  allowMigrants: {
    (migrants: (string | BigNumber)[], txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(migrants: (string | BigNumber)[], txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(migrants: (string | BigNumber)[], txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(migrants: (string | BigNumber)[], txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  asset(txDetails?: Truffle.TransactionDetails): Promise<[string, string]>;

  chain(txDetails?: Truffle.TransactionDetails): Promise<[string, BigNumber]>;

  completeSetup: {
    (txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  connecRollUpable: {
    (addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  connectChallengeable: {
    (addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  connectMigratable: {
    (addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  connectUserInteractable: {
    (addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(addr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  deregister: {
    (txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  finalize: {
    (arg0: string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  isProposable(proposerAddr: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<boolean>;

  propose: {
    (arg0: string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(arg0: string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  proxied(arg0: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<string>;

  register: {
    (txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  registerERC20: {
    (_erc20: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(_erc20: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(_erc20: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(_erc20: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  registerVk: {
    (
      txType: number | BigNumber | string,
      numOfInputs: number | BigNumber | string,
      numOfOutputs: number | BigNumber | string,
      alfa1: (number | BigNumber | string)[],
      beta2: (number | BigNumber | string)[][],
      gamma2: (number | BigNumber | string)[][],
      delta2: (number | BigNumber | string)[][],
      ic: (number | BigNumber | string)[][],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse>;
    call(
      txType: number | BigNumber | string,
      numOfInputs: number | BigNumber | string,
      numOfOutputs: number | BigNumber | string,
      alfa1: (number | BigNumber | string)[],
      beta2: (number | BigNumber | string)[][],
      gamma2: (number | BigNumber | string)[][],
      delta2: (number | BigNumber | string)[][],
      ic: (number | BigNumber | string)[][],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      txType: number | BigNumber | string,
      numOfInputs: number | BigNumber | string,
      numOfOutputs: number | BigNumber | string,
      alfa1: (number | BigNumber | string)[],
      beta2: (number | BigNumber | string)[][],
      gamma2: (number | BigNumber | string)[][],
      delta2: (number | BigNumber | string)[][],
      ic: (number | BigNumber | string)[][],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      txType: number | BigNumber | string,
      numOfInputs: number | BigNumber | string,
      numOfOutputs: number | BigNumber | string,
      alfa1: (number | BigNumber | string)[],
      beta2: (number | BigNumber | string)[][],
      gamma2: (number | BigNumber | string)[][],
      delta2: (number | BigNumber | string)[][],
      ic: (number | BigNumber | string)[][],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  withdrawReward: {
    (amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };
}

export interface MiMCInstance extends Truffle.ContractInstance {
  MiMCSponge(
    xL_in: number | BigNumber | string,
    xR_in: number | BigNumber | string,
    k: number | BigNumber | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<[BigNumber, BigNumber]>;
}

export interface TestERC20Instance extends Truffle.ContractInstance {
  allowance(owner: string | BigNumber, spender: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  approve: {
    (spender: string | BigNumber, amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(spender: string | BigNumber, amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<boolean>;
    sendTransaction(spender: string | BigNumber, amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(spender: string | BigNumber, amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  balanceOf(account: string | BigNumber, txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  decimals(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  decreaseAllowance: {
    (spender: string | BigNumber, subtractedValue: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(spender: string | BigNumber, subtractedValue: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<boolean>;
    sendTransaction(spender: string | BigNumber, subtractedValue: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(spender: string | BigNumber, subtractedValue: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  increaseAllowance: {
    (spender: string | BigNumber, addedValue: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(spender: string | BigNumber, addedValue: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<boolean>;
    sendTransaction(spender: string | BigNumber, addedValue: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(spender: string | BigNumber, addedValue: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  name(txDetails?: Truffle.TransactionDetails): Promise<string>;

  symbol(txDetails?: Truffle.TransactionDetails): Promise<string>;

  totalSupply(txDetails?: Truffle.TransactionDetails): Promise<BigNumber>;

  transfer: {
    (recipient: string | BigNumber, amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<Truffle.TransactionResponse>;
    call(recipient: string | BigNumber, amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<boolean>;
    sendTransaction(recipient: string | BigNumber, amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(recipient: string | BigNumber, amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  transferFrom: {
    (sender: string | BigNumber, recipient: string | BigNumber, amount: number | BigNumber | string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse
    >;
    call(
      sender: string | BigNumber,
      recipient: string | BigNumber,
      amount: number | BigNumber | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;
    sendTransaction(
      sender: string | BigNumber,
      recipient: string | BigNumber,
      amount: number | BigNumber | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      sender: string | BigNumber,
      recipient: string | BigNumber,
      amount: number | BigNumber | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };
}
