/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from '.';

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: 'Challengeable'): TruffleContracts.ChallengeableContract;
      require(name: 'Configurated'): TruffleContracts.ConfiguratedContract;
      require(name: 'Coordinatable'): TruffleContracts.CoordinatableContract;
      require(name: 'DepositChallenge'): TruffleContracts.DepositChallengeContract;
      require(name: 'DeserializationTester'): TruffleContracts.DeserializationTesterContract;
      require(name: 'HeaderChallenge'): TruffleContracts.HeaderChallengeContract;
      require(name: 'ICoordinatable'): TruffleContracts.ICoordinatableContract;
      require(name: 'IDepositChallenge'): TruffleContracts.IDepositChallengeContract;
      require(name: 'IERC20'): TruffleContracts.IERC20Contract;
      require(name: 'IERC721'): TruffleContracts.IERC721Contract;
      require(name: 'IHeaderChallenge'): TruffleContracts.IHeaderChallengeContract;
      require(name: 'IMigratable'): TruffleContracts.IMigratableContract;
      require(name: 'IMigrationChallenge'): TruffleContracts.IMigrationChallengeContract;
      require(name: 'IRollUpable'): TruffleContracts.IRollUpableContract;
      require(name: 'IRollUpChallenge'): TruffleContracts.IRollUpChallengeContract;
      require(name: 'ISetupWizard'): TruffleContracts.ISetupWizardContract;
      require(name: 'ITxChallenge'): TruffleContracts.ITxChallengeContract;
      require(name: 'IUserInteractable'): TruffleContracts.IUserInteractableContract;
      require(name: 'Layer2'): TruffleContracts.Layer2Contract;
      require(name: 'Layer2Controller'): TruffleContracts.Layer2ControllerContract;
      require(name: 'Migratable'): TruffleContracts.MigratableContract;
      require(name: 'MigrationChallenge'): TruffleContracts.MigrationChallengeContract;
      require(name: 'Migrations'): TruffleContracts.MigrationsContract;
      require(name: 'MiMC'): TruffleContracts.MiMCContract;
      require(name: 'Poseidon'): TruffleContracts.PoseidonContract;
      require(name: 'RollUpable'): TruffleContracts.RollUpableContract;
      require(name: 'RollUpChallenge'): TruffleContracts.RollUpChallengeContract;
      require(name: 'SetupWizard'): TruffleContracts.SetupWizardContract;
      require(name: 'SMT256'): TruffleContracts.SMT256Contract;
      require(name: 'TestERC20'): TruffleContracts.TestERC20Contract;
      require(name: 'TxChallenge'): TruffleContracts.TxChallengeContract;
      require(name: 'UserInteractable'): TruffleContracts.UserInteractableContract;
      require(name: 'ZkOptimisticRollUp'): TruffleContracts.ZkOptimisticRollUpContract;
      require(name: 'MiMC'): TruffleContracts.MiMCContract;
      require(name: 'Poseidon'): TruffleContracts.PoseidonContract;
      require(name: 'TestERC20'): TruffleContracts.TestERC20Contract;
    }
  }
}
